Data/urls.py
from django.urls import path
from .views import DataHome

app_name = 'targetdata'

urlpatterns = [
    path('', DataHome.as_view(), name='target_data_home')
]

Inventory/urls.py
from django.urls import include,path
from .views import ProductHome,DetailProduct, CreateProduct

app_name = 'inventory'

urlpatterns = [
    path('', ProductHome.as_view(), name='productlist'),
    path('<int:pk>/', DetailProduct.as_view(), name='productdetail'),
    path('create', CreateProduct.as_view(), name = 'productcreate'),
]

WorkDashboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('Dashboard.urls')),
    path('', include('Dashboard.urls')),
    path('products/', include('Inventory.urls')),
    path('invoices/', include('Invoices.urls')),
    path('targets/', include('Data.urls')),
]

Inventory/models.py
from django.db import models
from decimal import Decimal


class Product(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=200)
    cost = models.DecimalField(decimal_places=2, max_digits=10, default=Decimal(0.00))
    sale_price = models.DecimalField(decimal_places=2, max_digits=10)
    stock = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Product'

Inventory/forms.py
from django.forms import ModelForm
from .models import Product


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'cost', 'sale_price']

Inventory/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views import View
from django.views.generic import ListView, DetailView, UpdateView
from .models import Product
from .forms import ProductForm


class ProductHome(ListView):
    model = Product


class CreateProduct(View):
    template_name = 'Inventory/product-create.html'

    def get(self, request):
        form = ProductForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request):
        form = ProductForm(request.POST)
        ctx = {'form': form}

        if form.is_valid():
            new_prod = Product.objects.create(
                name=form.cleaned_data['name'],
                description=form.cleaned_data['description'],
                cost=form.cleaned_data['cost'],
                sale_price=form.cleaned_data['sale_price'],
            )
            new_prod.save()
            return HttpResponseRedirect('/products')

        else:
            form = ProductForm()
        return render(request, self.template_name, ctx)


# class UpdateProduct(UpdateView):
#     def get(self):
#         pass
#
#     def post(self):
#         pass
#
#
class DetailProduct(DetailView):
    model = Product
    template_name = 'Inventory/product-detail.html'

    def get(self, request, pk):
        obj = Product.objects.get(id=pk)
        ctx = {'product': obj}
        return render(request, self.template_name, ctx)

# class DeleteProduct(View):
#     def get(self):
#         pass
#
#     def post(self):
#         pass

Inventory/templates/Inventory/product-create.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}Add Product{% endblock title %}

{% block body %}
<div class="container">
    <div class="row align-self-center justify-content-center text-center">
        <div class="col-12 my-5">
            <form action="{% url 'inventory:productcreate' %}" method="post">
                {% csrf_token %}
                <h1 class="display-4">Add a new Product</h1>
                {{ form|crispy }}
                <br>
                <input type="submit">
            </form>
        </div>
    </div>
</div>
{% endblock body %}

Inventory/templates/Inventory/product-detail.html
{% extends "base.html" %}

{% block title %}Product Info{% endblock title %}

{% block body %}
    <div class="container">

        <div class="row text-center">
            <div class="col">
                <a href="{% url 'inventory:productlist' %}">Go Back</a>
            </div>
        </div>

        <div class="row justify-content-md-center text-center">
            <div class="col-md-12 align-items-center">
                <h1 class="display-1 font-weight-bold">{{ product.name }}</h1>
                <hr>
            </div>
        </div>

        <div class="row justify-content-center text-center">
            <div class="col-4">
                <p class="lead">{{ product.description }}</p>
            </div>
        </div>

        <div class="row justify-content-between text-center">
            <div class="col-12">
                <hr>
                <p class="lead font-weight-bold">Price of Materials : {{ product.cost }}</p>
                <p class="lead font-weight-bold">Sells for : {{ product.sale_price }}</p>
            </div>
        </div>
    </div>
{% endblock body %}

Inventory/templates/Inventory/product_list.html
{% extends "base.html" %}

{% block title %}Products{% endblock title %}

{% block body %}
<div class="container">
    <div class="row mx-5 justify-content-around text-center">
        <div class="col-12">
            <h3 class="display-5 py-2">Products</h3>

            <div class="list-group py-2 text-center">
                {% for product in product_list %}

                    <a style="font-size: 28px" href="{% url 'inventory:productdetail' product.id %}" class="list-group-item list-group-item-action py-2" aria-current="true">
                        {{ product }}
                    </a>

                {% endfor %}
                <a class="list-group-item list-group-item-action py-2" href="{% url 'inventory:productcreate' %}"><h2>Add a new product!</h2></a>
            </div>
        </div>
    </div>
</div>
{% endblock body %}