Data/urls.py
from django.urls import path
from .views import DataHome

app_name = 'targetdata'

urlpatterns = [
    path('', DataHome.as_view(), name='target_data_home')
]

Invoices/urls.py
from django.urls import include, path
from .views import InvoiceHome, InvoiceCreate, InvoiceDetail, InvoiceDelete


app_name = 'invoices'

urlpatterns = [
    path('', InvoiceHome.as_view(), name='invoice-home'),
    path('create', InvoiceCreate.as_view(), name='invoice-create'),
    path('<int:pk>/', InvoiceDetail.as_view(), name='invoice-detail'),
    path('<int:pk>/delete', InvoiceDelete.as_view(), name='invoice-delete'),
]

WorkDashboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('Dashboard.urls')),
    path('', include('Dashboard.urls')),
    path('products/', include('Inventory.urls')),
    path('invoices/', include('Invoices.urls')),
    path('targets/', include('Data.urls')),
]

Invoices/models.py
from django.db import models
from Inventory.models import Product


class Invoice(models.Model):
    date = models.DateField(null=True)
    products = models.ManyToManyField(Product, related_name='proditem', through='Item', null=True)

    def __str__(self):
        return 'Invoice #' + str(self.pk)

    def total(self):
        total = 0
        for thing in self.item_set.all():
            total += thing.total()
        return total

    class Meta:
        verbose_name = 'Invoice'


class Item(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, blank=True, null=True)
    quantity = models.PositiveIntegerField(default=1)
    sales_channel = models.CharField(max_length=100, default='Generic Sale')

    def __str__(self):
        return self.product.name

    def total(self):
        return self.quantity * self.product.sale_price

    class Meta:
        verbose_name = 'Item'

Invoices/forms.py
from django import forms
from django.forms import ModelForm
from Invoices.models import Invoice, Item

from Inventory.models import Product


class InvoiceForm(forms.Form):
    date = forms.DateField()




class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = '__all__'



    # product = models.ModelChoiceField(Product.objects.all())
    # invoice = models.ModelChoiceField(Invoice.objects.all())

Invoices/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from django.views import View
from django.views.generic import CreateView, ListView, DetailView, DeleteView
from Invoices.models import Item, Invoice
from Inventory.models import Product
from django.urls import reverse_lazy
from Invoices.forms import ItemForm, InvoiceForm
from django.forms import inlineformset_factory


class InvoiceHome(ListView):
    model = Invoice
    template_name = 'Invoices/invoice-home.html'



class InvoiceCreate(View):
    template_name = 'Invoices/invoice-create.html'
    success_url = reverse_lazy('invoices:invoice-home')
    InvoiceFormSet = inlineformset_factory(Invoice, Item, fields=('product', 'quantity'), extra=5)

    def get(self, request):
        formset = self.InvoiceFormSet()
        ctx = {'formset': formset}
        return render(request, self.template_name, ctx)

    def post(self, request):
        formset = self.InvoiceFormSet(request.POST)
        ctx = {'formset': formset}
        print(request.POST.keys())
        # if formset.is_valid():
        #     new_invoice = Invoice.objects.create(date=request.POST['date'])
        #     new_invoice.save(commit=False)
        # else:
        #     print(formset.errors)
        #
        #         new_invoice.save()
        #         item.save()
        #     else:
        #         item = Item.objects.create(
        #             product=form.cleaned_data['product'],
        #             invoice=form.cleaned_data['invoice'],
        #             quantity=form.cleaned_data['quantity'],
        #             sales_channel=form.cleaned_data['sales_channel'],
        #         )
        #         form.cleaned_data['invoice'].date = request.POST['date']
        #         item.save()
        #
        #     return HttpResponseRedirect('/invoices')

        # else:
        #     form = ItemForm()
        return render(request, self.template_name, ctx)


class InvoiceDetail(View):
    template_name = 'Invoices/invoice-detail.html'

    def get(self, request, pk):
        invoice = Invoice.objects.get(pk=pk)
        ctx = {'invoice': invoice}
        # for item in zipped_ctx:
        #     print(item)
        return render(request, self.template_name, ctx)


class InvoiceDelete(DeleteView):
    model = Invoice
    template_name = 'Invoices/invoice-delete.html'
    success_url = reverse_lazy('invoices:invoice-home')

Invoices/templates/Invoices/invoice-create.html
{%  extends "base.html" %}
{% load crispy_forms_filters %}

{%  block title %}Create Invoice{%  endblock title %}

{% block head %}
    <script>
        $( function() {
            $( "#id_date" ).datepicker({ dateFormat: 'mm-dd-yy' });
        } );
    </script>
{% endblock head %}

{% block body %}
    <div class="container">

        <div class="row text-center my-2">
            <div class="col">
                <h1 class="display-3">Create a new Invoice</h1>
            </div>
        </div>

        <div class="row align-self-center justify-content-center text-center">
            <div class="col-12 my-3">
                <form method="post">{% csrf_token %}
                    <br>
                    <input class="my-3" id="id_date" name="date"
                           value="Invoice Date"
                           min="01-01-2018" max="12-31-2030">
                    <br>

                    {%  for form in formset %}
                        {{ form.product }}
                        {{ form.quantity }}
                        <br>
                    {% endfor %}

                    <hr>
                    <input label="Quantity" type="submit" value="Save">
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

Invoices/templates/Invoices/invoice-delete.html
{% extends "base.html" %}

{% block title %}Delete{% endblock title %}

{% block body %}
    <div class="container">
        <div class="row justify-content-center text-center">
            <div class="col">
                <h1 class="display-5">Delete Invoice?</h1>

                <p class="lead">Are you sure you want to delete {{ invoice }}?</p>

                <form action="" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="Yes, Delete.">
                </form>
            </div>
        </div>
    </div>
{% endblock body %}

Invoices/templates/Invoices/invoice-detail.html
{% extends "base.html" %}
{% load humanize %}

{% block title %}Invoice Detail{% endblock title %}

{% block body %}
<div class="container">
    <div class="row text-center">
        <div class="col">
            <a href="{% url 'invoices:invoice-home' %}">Go Back</a>
        </div>
    </div>
    <div class="row text-center my-2">
        <div class="col">
            <h1 class="display-3">{{ invoice }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Product</th>
                    <th scope="col">Cost</th>
                    <th scope="col">Sell Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total</th>
                </tr>
                </thead>
                <tbody>
                {% for thing in invoice.item_set.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ thing }}</td>
                    <td>{{ thing.product.cost|intcomma }}</td>
                    <td>{{ thing.product.sale_price|intcomma }}</td>
                    <td>{{ thing.quantity }}</td>
                    <td>{{ thing.total|intcomma }}</td>
                </tr>
                {% endfor %}
                <tf>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>Invoice Total</td>
                    <td>{{ invoice.total|intcomma }}</td>
                </tf>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock body %}

Invoices/templates/Invoices/invoice-home.html
{% extends "base.html" %}

{% block title %}Invoices{% endblock %}

{% block body %}
    <div class="container">
        <div class="row mx-5 justify-content-between text-center">
            <div class="col-12">

                <h3 class="display-5 py-2">Invoices</h3>

                {% if invoice_list|length == 0 %}
                    <h4>No invoices yet!</h4>
                {% endif %}

                {% for invoice in invoice_list %}
                    <p class="lead"><a href="{% url 'invoices:invoice-detail' invoice.id %}">{{ invoice }}</a>{% if invoice.date %} - {{ invoice.date }}{% endif %}
                        <button type="button" onclick="document.location='{% url 'invoices:invoice-delete' invoice.id %}'" class="btn btn-outline-danger btn-sm mx-2">Delete</button></p>
                {% endfor %}
                <h3 class="py-3"><a href="{% url 'invoices:invoice-create' %}">Create new Invoice</a></h3>

            </div>
        </div>
    </div>
{% endblock body %}