Dashboard/urls.py
from django.contrib import admin
from django.urls import path
from Dashboard.views import DashboardHome, PieChart

app_name = 'dashboard'
urlpatterns = [
    path('', DashboardHome.as_view(), name='index'),
    path('salespie', PieChart.as_view(), name='pie'),
]

Data/urls.py
from django.urls import path
from .views import DataHome

app_name = 'targetdata'

urlpatterns = [
    path('', DataHome.as_view(), name='target_data_home')
]

Inventory/urls.py
from django.urls import include,path
from .views import ProductHome,DetailProduct, CreateProduct

app_name = 'inventory'

urlpatterns = [
    path('', ProductHome.as_view(), name='productlist'),
    path('<int:pk>/', DetailProduct.as_view(), name='productdetail'),
    path('create', CreateProduct.as_view(), name = 'productcreate'),
]

WorkDashboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('Dashboard.urls')),
    path('', include('Dashboard.urls')),
    path('products/', include('Inventory.urls')),
    path('invoices/', include('Invoices.urls')),
    path('targets/', include('Data.urls')),
]

Dashboard/models.py
from django.db import models

# Create your models here.

Dashboard/forms.py
from django import forms


class DateForm(forms.Form):
    start_date = forms.DateField()
    end_date = forms.DateField()

Dashboard/views.py
import datetime
from django.shortcuts import render, HttpResponseRedirect
from django.views import View
from django.core.exceptions import ValidationError
from Invoices.models import Item, Invoice
from Data.models import Data
from Dashboard.forms import DateForm
from Dashboard.services import (
    total_invoices,get_total_tuple,
    get_date_tuple, make_pie_graph,
    make_line_graph)


class DashboardHome(View):
    template_name = 'Dashboard/index.html'

    def get(self, request):
        all_invoices = Invoice.objects.all().order_by('date')
        data = (get_date_tuple(all_invoices), get_total_tuple(all_invoices))
        make_line_graph(data)
        form = DateForm()
        ctx = {'data': data, 'form': form}

        return render(request, self.template_name, ctx)

    def post(self, request):
        form = DateForm(request.POST)
        print(form.errors)
        if form.is_valid():
            print()
            print("Valid")
            print()
            invoices = Invoice.objects.filter(
                date__range=[request.POST['start_date'], request.POST['end_date']]
            ).order_by('date')
            data = (get_date_tuple(invoices), get_total_tuple(invoices))
            make_line_graph(data)
            ctx = {'data': data}
            return render(request, self.template_name, ctx)
        else:
            form = DateForm()
            return render(request, self.template_name, {'form': form})


class PieChart(View):
    template_name = 'Dashboard/pie.html'

    def get(self, request):
        all_invoices = Invoice.objects.all().order_by('date')
        last_six_month = Invoice.objects.filter(
            date__range=[datetime.date.today() - datetime.timedelta(weeks=24), datetime.date.today()]
        )
        total_sales = sum(get_total_tuple(all_invoices))
        last_six_month_sales = sum(get_total_tuple(last_six_month))
        data = (total_sales, Data.objects.get(pk=1).monthly_sales)
        six_month_data = (last_six_month_sales, Data.objects.get(pk=1).monthly_sales)
        make_pie_graph(data, 0)
        make_pie_graph(six_month_data, 1)
        ctx = {'sales': total_sales}

        return render(request, self.template_name, ctx)

    def post(self, request):
        pass

Dashboard/templates/Dashboard/index.html
{% extends "base.html" %}

{% block title %}Sales Dashboard{% endblock title %}

{% block head %}
    {# Date picker/jQuery CDN #}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css" integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js" integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k=" crossorigin="anonymous"></script>
    <script>
        $(function () {
            $("#id_start_date").datepicker({
                format:'mm/dd/yyyy',
            });
        });
        $(function () {
            $("#id_end_date").datepicker({
                format:'mm/dd/yyyy',
            });
        });
    </script>
{% endblock head %}

{% block body %}
    {% block graphbutton %}

    <div class="container">

        <div class="row text-center my-3">

            <div class="col-12">
                <h1>Your business trends at a glance</h1>

                {# Dropdown links for changing graph type to display #}
                <div class="dropdown">
                    <a class="btn btn-secondary dropdown-toggle my-3" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        Change Graph
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'dashboard:index' %}">Sales Line Graph</a></li>
                        <li><a class="dropdown-item" href="{% url 'dashboard:pie' %}">Profit Pie Chart</a></li>
                        <li><a class="dropdown-item" href="#">Another Graph of some sort</a></li>
                    </ul>
                </div>

                {# Form class with date pickers for start and end date #}
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Submit">
                </form>

                <hr>

                {# Block for inserting html graph snippet #}
                {% block graph %}
                    {% include "Dashboard/GraphSnippets/graph.html" %}
                {% endblock graph %}

                <a href="{% url 'inventory:productlist' %}">View Your Products</a>

            </div>
        </div>
    </div>

    {% endblock graphbutton %}
{% endblock body %}

Dashboard/templates/Dashboard/pie.html
{% extends "Dashboard/index.html" %}

{% block title %}Sales Dashboard{% endblock title %}

{% block graph %}
    <div class="row text-center my-3">
        <div class="col-6">
            {% include "Dashboard/GraphSnippets/piesales0.html" %}
        </div>
        <div class="col-6">
            {% include "Dashboard/GraphSnippets/piesales1.html" %}
        </div>
    </div>
{% endblock %}