Dashboard/urls.py
from django.contrib import admin
from django.urls import path
from Dashboard.views import DashboardHome, PieChart

app_name = 'dashboard'
urlpatterns = [
    path('', DashboardHome.as_view(), name='index'),
    path('salespie', PieChart.as_view(), name='pie'),
]

Data/urls.py
from django.urls import path
from .views import DataHome

app_name = 'targetdata'

urlpatterns = [
    path('', DataHome.as_view(), name='target_data_home')
]

Inventory/urls.py
from django.urls import include,path
from .views import ProductHome,DetailProduct, CreateProduct

app_name = 'inventory'

urlpatterns = [
    path('', ProductHome.as_view(), name='productlist'),
    path('<int:pk>/', DetailProduct.as_view(), name='productdetail'),
    path('create', CreateProduct.as_view(), name = 'productcreate'),
]

Invoices/urls.py
from django.urls import include, path
from .views import InvoiceHome, InvoiceCreate, InvoiceDetail, InvoiceDelete


app_name = 'invoices'

urlpatterns = [
    path('', InvoiceHome.as_view(), name='invoice-home'),
    path('create', InvoiceCreate.as_view(), name='invoice-create'),
    path('<int:pk>/', InvoiceDetail.as_view(), name='invoice-detail'),
    path('<int:pk>/delete', InvoiceDelete.as_view(), name='invoice-delete'),
]

WorkDashboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('Dashboard.urls')),
    path('', include('Dashboard.urls')),
    path('products/', include('Inventory.urls')),
    path('invoices/', include('Invoices.urls')),
    path('targets/', include('Data.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%  block title %}Sales Dashboard{% endblock %}</title>
    {% block imports %}
        <!-- Latest compiled and minified CSS -->

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    {% endblock imports %}
    {% block head %}

    {% endblock head %}
</head>

<body>

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url "dashboard:index" %}">QuickTrends</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav my-1 ms-3">

                    <li class="nav-item me-auto">
                        <a class="nav-link active" aria-current="page" href="{% url "dashboard:index" %}">Home</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Products
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'inventory:productlist' %}">View Products</a></li>
                            <li><a class="dropdown-item" href="{% url 'inventory:productcreate' %}">Add a Product</a></li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Invoice
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'invoices:invoice-home' %}">View Invoices</a></li>
                            <li><a class="dropdown-item" href="{% url 'invoices:invoice-create' %}">Create Invoice</a></li>
                        </ul>
                    </li>

                </ul>
                <ul class="navbar-nav ms-auto me-3">
                    <li class="nav-item"><a class="nav-link active ml-auto" href="{% url 'targetdata:target_data_home' %}">Targets</a></li>
                </ul>
            </div>
        </div>
    </nav>
{% endblock navbar%}

{% block body %}


{% endblock body %}

{% block js %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
{% endblock js %}
</body>
</html>